#!/bin/zsh

#############################
# variables d'environnement #
#############################

export MANPATH="/usr/local/man:$MANPATH"

plugins=(gedit)
export PATH="${PATH}:/usr/local/bin"
export PATH="${PATH}:/usr/bin:/bin:"
export PATH="${PATH}:/usr/sbin:/sbin"


export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'
####---------------------------------------------------####

DEFAULT_USER=alex
export hostname=`hostname -s`
export WORK_PATH="$HOME/work"
export APP_PATH="${WORK_PATH}/app"

export PATH="${HOME}/.local/bin:$PATH"
export WORK_PATH="$HOME/work"

export CYCLUS_PATH="${APP_PATH}/cyclus"
export SERPENT_DATA="${WORK_PATH}/data"

export GOPATH="${APP_PATH}/go"
export PATH="${PATH}:${GOPATH}/bin"

####---------------------------------------------------####

export kermit='kermit.ep.wisc.edu'
export ovh='vps204419.ovh.net'
export pi='192.168.1.5'
export git='git@github.com:Baaaaam/'
export glab='git@gitlab.in2p3.fr:baaaaam/'

# PATH for MCNP executables
export PATH
PATH="/home/alex/opt/MCNP/MCNP_CODE/bin:/home/alex/bin:/home/alex/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"


# DATAPATH for MCNP cross-section data
export DATAPATH
DATAPATH="/home/alex/opt/MCNP/MCNP_DATA"
 
alias matlab='/usr/local/bin/matlab'
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
export PATH=$PATH:/home/alex/install/moab/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/alex/install/moab/lib
alias pyne-install="python setup.py install --user -- -DMOAB_LIBRARY=/home/alex/install/moab/lib/libMOAB.so -DMOAB_INCLUDE_DIR=/home/alex/install/moab/include"
alias condor="ssh aaswenson@aci-service-1.chtc.wisc.edu"
alias wifi="sudo service network-manager restart"
export PYTHONPATH=$HOME/.local/lib/python2.7/site-packages/PyTAPS-1.4-py2.7-linux-x86_64.egg
export PATH=$PATH:/home/alex/opt/scale6.1/cmds/batch6.1
alias batch6.1="~/opt/scale6.1/cmds/batch6.1"
alias python="python -B"
alias python3="python3 -B"


